### ISSUE TITLE
Error running demo in FSI

### ISSUE THREAD

**Issue by Mark-Broadhurst** [Dzoukr/Shaver#3]
So I was going to try this out as I'm looking for a good HTML template engine for Fsharp

Just doing the following example from your read me in FSI 
```
#r "packages/Suave/lib/net40/Suave.dll"
#r "packages/Shaver/lib/net45/Shaver.dll"
#r "packages/RazorEngine/lib/net45/RazorEngine.dll"
#r "packages/Microsoft.AspNet.Razor/lib/net40/System.Web.Razor.dll"

open Suave
open Shaver.Razor

type MyModel = { Message: string }

let app = singlePage "SinglePage.html" { Message = "Hello Shaver"}

startWebServer defaultConfig app
```

it starts up fine however on running the page I get 

```
[E] 2016-11-17T14:27:17.1187548Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.TypeLoadException: Inheritance security rules violated while overriding member: 'RazorEngine.Compilation.CSharp.CSharpRazorCodeLanguage.CreateCodeGenerator(System.String, System.String, System.String
, System.Web.Razor.RazorEngineHost)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.
   at RazorEngine.Compilation.CSharp.CSharpDirectCompilerService..ctor(Boolean strictMode, Func`1 markupParserFactory)
   at RazorEngine.Compilation.DefaultCompilerServiceFactory.CreateCompilerService(Language language)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
   at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at Shaver.Razor.partial@52.Invoke(Unit unitVar) in C:\Dzoukr\FSharp\Shaver\src\Shaver\Razor.fs:line 52
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)

[E] 2016-11-17T14:27:17.4312756Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.TypeLoadException: Inheritance security rules violated while overriding member: 'RazorEngine.Compilation.CSharp.CSharpRazorCodeLanguage.CreateCodeGenerator(System.String, System.String, System.String
, System.Web.Razor.RazorEngineHost)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.
   at RazorEngine.Compilation.CSharp.CSharpDirectCompilerService..ctor(Boolean strictMode, Func`1 markupParserFactory)
   at RazorEngine.Compilation.DefaultCompilerServiceFactory.CreateCompilerService(Language language)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
   at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at Shaver.Razor.partial@52.Invoke(Unit unitVar) in C:\Dzoukr\FSharp\Shaver\src\Shaver\Razor.fs:line 52
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
```

Any ideas am I doing something stupid?

**Comment by Mark-Broadhurst** [comment]
Ok So I dont think I'm doing something stupid as I've run it on a console application and it works fine.

However I've also recreated the RazorEngine rendering the page and it seems to originate from there.

**Comment by Dzoukr** [comment]
Thanks for info, @Mark-Broadhurst. I will look at it anyway - need to "remove dust" from this project. :)
